"""tabela_filme

Revision ID: 1c6a868216f5
Revises: 
Create Date: 2024-09-06 13:33:38.873747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c6a868216f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filme',
    sa.Column('id_filme', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('diretor', sa.String(length=100), nullable=True),
    sa.Column('ano_lancamento', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_filme')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filme')
    # ### end Alembic commands ###
