"""pode

Revision ID: 6555b14e0a0f
Revises: 
Create Date: 2024-09-10 13:13:16.102252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6555b14e0a0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filme',
    sa.Column('id_filme', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('diretor', sa.String(length=100), nullable=True),
    sa.Column('ano_lancamento', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_filme')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filme')
    # ### end Alembic commands ###
